// Use these if you want to test with dummy code without using a data base

let DUMMY_USER = [
	{
		userName: "GilbertWalker57823",
		fullName: "Gilbert Walker",
		displayFullName: true,
		email: "Gilbert.Walker@gmail.com",
		password: "12345",
		profilePicture: "",
		bio: "Et facere dolorum officiis sapiente corrupti ratione. Repellendus et sed quod sit id molestiae. Molestiae ex reprehenderit autem magni quae sed et ut ut.",
		joinDate: "Jan. 13, 2024",
		totalAmountOfLikes: 4,
		numberOfPosts: 0,
		uuid: 1111,
	},
	{
		userName: "LaurencePollich5733",
		fullName: "Laurence Pollich",
		displayFullName: false,
		email: "Laurence.Pollich@gmail.com",
		password: "54321",
		profilePicture: "",
		bio: "Est maxime provident at. Ipsum natus sapiente. Repellat quia et sunt et beatae velit. Rem quod molestias odit debitis earum quae similique.",
		joinDate: "Jul. 28, 2023",
		totalAmountOfLikes: 64,
		numberOfPosts: 0,
		uuid: 2222,
	},
	{
		userName: "Malcolm Marquardt43y3",
		fullName: "Malcolm Marquardt",
		displayFullName: true,
		email: "firstname.lastname@gmail.com",
		password: "",
		profilePicture: "",
		bio: "Occaecati similique omnis ratione inventore non. Nisi quod nihil. Perferendis fugit incidunt dolores adipisci. Et accusamus non et ut consequatur iste perspiciatis ipsa.",
		joinDate: "Dec. 16, 2023",
		totalAmountOfLikes: 2,
		numberOfPosts: 0,
		uuid: 3333,
	},
	{
		userName: "Duane Osinski33253",
		fullName: "Miss Duane Osinski",
		displayFullName: true,
		email: "firstname.lastname@gmail.com",
		password: "",
		profilePicture: "",
		bio: "Fuga dicta culpa modi. Eum quis et magni voluptatum non modi. Temporibus cum nemo cupiditate quo sed qui molestiae ut pariatur.",
		joinDate: "Jan. 22, 2024",
		totalAmountOfLikes: 56,
		numberOfPosts: 0,
		uuid: 4444,
	},
	{
		userName: "Ms. Alexandra",
		fullName: "Ms. Alexandra Rippin",
		displayFullName: false,
		email: "firstname.lastname@gmail.com",
		password: "",
		profilePicture: "",
		bio: "Aliquam eligendi praesentium corporis voluptatum voluptatem. Molestiae iste ratione alias qui id fugit praesentium. Quasi delectus itaque. Et porro consequatur accusantium. Excepturi est ratione illum perferendis et delectus corrupti perferendis.",
		joinDate: "Oct. 30, 2023",
		totalAmountOfLikes: 63,
		numberOfPosts: 0,
		uuid: 5555,
	},
];

module.exports = DUMMY_USER;
